# docker-compose.yml
version: '3'
services:
  database:
    container_name: "timeseries_db"
    restart: "always"
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./data.sh:/docker-entrypoint-data.d/data.sh
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
      - type: bind
        source: ./TSA_Dataset.csv
        target: /data/TSA_Dataset.csv
    ports: 
      - 5432:5432
  python_env:
    build: .
    container_name: "python_env"
    restart: "always"
    ports:
      - 8000:8000
    env_file:
      - database.env # configure postgres
    volumes:
      - type: bind
        source: ./test_query.py
        target: /scripts/test_query.py
    depends_on:
        - database


volumes:
  database-data: # named volumes can be managed easier using docker-compose

